version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: medusa-postgres
    environment:
      POSTGRES_DB: medusa-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
